import os
CONFIRM_ZONE_VAR = 'CONFIRM_ZONE'
CONFIRM_PROCESS_LOG_VAR = 'CONFIRM_PROCESS_LOG'
CONFIRM_PROCESS_PATH_VAR = 'CONFIRM_PROCESS_PATH'
CONFIRM_PRODUCT_VAR = 'CONFIRM_PRODUCT'
CONFIRM_PROD_ENV_ID_VAR = 'CONFIRM_PROD_ENV_ID'
CONFIRM_ENVIRONMENT_VAR = 'CONFIRM_ENVIRONMENT'
CONFIRM_REPO_NAME_VAR = 'CONFIRM_REPO_NAME'
CONFIRM_TIMESTAMP_ID_VAR = 'CONFIRM_TIMESTAMP_ID'
CONFIRM_FID_VAR = 'CONFIRM_FID'

CONFIRM_ZONE = os.environ.get(CONFIRM_ZONE_VAR)
CONFIRM_PROCESS_PATH = os.environ.get(CONFIRM_PROCESS_PATH_VAR)
CONFIRM_PROCESS_LOG = os.environ.get(CONFIRM_PROCESS_LOG_VAR)
CONFIRM_PRODUCT = os.environ.get(CONFIRM_PRODUCT_VAR)
CONFIRM_PROD_ENV_ID = os.environ.get(CONFIRM_PROD_ENV_ID_VAR)
CONFIRM_ENVIRONMENT = os.environ.get(CONFIRM_ENVIRONMENT_VAR)
CONFIRM_REPO_NAME = os.environ.get(CONFIRM_REPO_NAME_VAR)
CONFIRM_TIMESTAMP_ID = os.environ.get(CONFIRM_TIMESTAMP_ID_VAR)
CONFIRM_FID = os.environ.get(CONFIRM_FID_VAR)
