ENC_CONFIG_PATH = '/backup/enc/.config.yaml'
ENC_PROCESS_DIR = '/backup/enc/process'
VERIFIED_DIR = '/backup/enc/verified'
FAILED_DIR = '/backup/enc/failed'
RELEASE_DIR = '/backup/ready'
PUBLISH_DIR = '/backup/public'
